const LandObj = {
  en_US: {
    please_enter_account: "Please enter a username. ",
    please_enter_pwd: "Please enter a password.",
    please_enter_access_code: "Please enter an access code.",
    login: "Login",
    accesscode: "Access Code",
    password: "Password",
    account: "Account",
    or: "or",
    one_click_login: "One-click Login",
    account_login: "Account Login",
    voucher_login: "Voucher Login",
    venue_location: "Venue Location: ",
    contact_whatsapp: "Contact on WhatsApp",
    connecting: "Connecting to WiFi\u2026",
    connected: "Connected! Opening review page\u2026",
    connection_failed: "Connection failed. Please try again.",
  },
  es_ES: {
    please_enter_account: "Introduzca el nombre de usuario.",
    please_enter_pwd: "Introduzca la contraseña.",
    please_enter_access_code: "por favor ingrese el código de verificación.",
    login: "Iniciar sesión",
    accesscode: "Código de acceso",
    password: "Contraseña",
    account: "Cuenta",
    or: "o",
    one_click_login: "Un solo clic",
    account_login: "Cuenta",
    voucher_login: "Gutschein-Anmeldung",
    venue_location: "Ubicación del lugar: ",
    contact_whatsapp: "Contactar por WhatsApp",
    connecting: "Conectando al WiFi\u2026",
    connected: "\u00a1Conectado! Abriendo página de reseña\u2026",
    connection_failed: "Conexión fallida. Por favor, inténtelo de nuevo.",
  },
};
